name: webilastik
channels:
  - ilastik-forge
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - numpy
  - fastfilters
  - fs
  - lemon
  - vigra
  - scikit-image
  - scikit-learn
  - h5py
  - typing_extensions
  - aiohttp
  - requests
  - redis-py
  - pip
  - pip:
    - git+https://git@github.com/ilastik/ndstructs@f70de7c61f55d22c237bc032cb364e06199afb09
