name: webilastik
channels:
  - defaults
  - conda-forge
  - ilastik-forge/label/freepy
dependencies:
  - python>=3.8
  - numpy
  - fastfilters
  - fs
  - lemon
  - vigra
  - scikit-image
  - scikit-learn
  - h5py
  - typing_extensions
  - aiohttp
  - requests
  - redis-py
  - pip
  - pip:
    - git+https://git@github.com/ilastik/ndstructs@dev
