version: '3'

vars:
  CWD:
    sh: pwd
  BUILD_DIR: "{{.CWD}}/build"
  PKG_VERSION: "0.1.1"
  PKG_NAME: webilastik_{{.PKG_VERSION}}
  ENV_PATH: "{{.BUILD_DIR}}/{{.PKG_NAME}}_conda_env"
  PACKED_ENV_PATH: "{{.ENV_PATH}}.tar.gz"
  PKG_TREE_PATH: "{{.BUILD_DIR}}/{{.PKG_NAME}}"
  DEB_PKG_PATH: "{{.BUILD_DIR}}/{{.PKG_NAME}}.deb"

tasks:
  create-build-dir: mkdir -p {{.BUILD_DIR}}

  create-conda-environment:
    deps: [create-build-dir]
    sources: ["../environment.yml"]
    vars:
      ENV_CHECKSUM_PATH: "{{.BUILD_DIR}}/environment.yml.sha256"
    cmds:
      - conda env create --prefix {{.ENV_PATH}} -f ../environment.yml
      - sha256sum ../environment.yml > {{.ENV_CHECKSUM_PATH}}
    status:
      - sha256sum ../environment.yml > {{.ENV_CHECKSUM_PATH}}.check
      - diff {{.ENV_CHECKSUM_PATH}}.check {{.ENV_CHECKSUM_PATH}}

  create-packed-conda-environment:
    deps: [create-conda-environment]
    sources: ["{{.PACKED_ENV_PATH}}"]
    generates: ["{{.PACKED_ENV_PATH}}"]
    cmds:
      - conda pack -p {{.ENV_PATH}} -o {{.PACKED_ENV_PATH}}

  create-deb-package:
    deps: [create-conda-environment]
    sources:
      - "{{.PACKED_ENV_PATH}}"
    generates:
      - "{{.DEB_PKG_PATH}}"
    status:
      - "false" #FIXME

    vars:
      CONTROL_FILE_CONTENTS: |-
          Package: webilastik
          Version: {{.PKG_VERSION}}
          Section: base
          Priority: optional
          Architecture: amd64
          Depends:
          Maintainer: ilastik Team <team@ilastik.org>
          Description: Webilastik
           Server and frontend for the web version of ilastik
    cmds:
      - rm -rf {{.PKG_TREE_PATH}}
      - cp -r ./package_tree {{.PKG_TREE_PATH}}
      - mkdir -p {{.PKG_TREE_PATH}}/etc/webilastik
      - echo '{{.CONTROL_FILE_CONTENTS}}' > {{.PKG_TREE_PATH}}/DEBIAN/control
      - mkdir -p {{.PKG_TREE_PATH}}/opt/webilastik_conda_env
      - tar -xzf {{.PACKED_ENV_PATH}} -C {{.PKG_TREE_PATH}}/opt/webilastik_conda_env
      - mkdir -p {{.PKG_TREE_PATH}}/opt/webilastik
      - cp -r ../webilastik ../overlay {{.PKG_TREE_PATH}}/opt/webilastik
      - find {{.PKG_TREE_PATH}}/opt/webilastik -name __pycache__ | xargs --no-run-if-empty rm -rf
      - dpkg-deb --build {{.PKG_TREE_PATH}} {{.DEB_PKG_PATH}}

  clean: rm -rf {{.BUILD_DIR}}/*

  default:
    deps: [create-deb-package]

